# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-30 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_count', models.IntegerField(default=1)),
                ('travel_city', models.CharField(max_length=225)),
                ('travel_data', models.CharField(max_length=225)),
                ('travel_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('name1', models.CharField(max_length=225)),
                ('name2', models.CharField(max_length=225)),
                ('name3', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.City'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
